<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/24 13:37:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=srikby_orangehrm',
  'username' => 'srikby_orangehrm',
  'password' => 'Excent@123',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
